const OfferABI = [
	{
		inputs: [
			{ internalType: 'address', name: 'wbnbAddress_', type: 'address' },
			{
				internalType: 'address',
				name: 'rewardsContractAddress_',
				type: 'address',
			},
			{
				internalType: 'address',
				name: 'routerAddress_',
				type: 'address',
			},
			{ internalType: 'address', name: 'devWallet_', type: 'address' },
		],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'adr',
				type: 'address',
			},
		],
		name: 'Authorized',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'nftOfferId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'wantedNftAddress',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'wantedNftId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'soldNftAddress',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256[]',
				name: 'soldNftIds',
				type: 'uint256[]',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'buyer',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'index',
				type: 'uint256',
			},
		],
		name: 'NftOfferCreated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'nftOfferId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'wantedNftAddress',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'wantedNftId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'soldNftAddress',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256[]',
				name: 'soldNftIds',
				type: 'uint256[]',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'buyer',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'bytes32',
				name: 'status',
				type: 'bytes32',
			},
		],
		name: 'NftOfferUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'owner',
				type: 'address',
			},
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'tokenOfferId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'nftAddress',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'nftId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'tokenAddress',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'price',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'buyer',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'index',
				type: 'uint256',
			},
		],
		name: 'TokenOfferCreated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'tokenOfferId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'nftAddress',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'nftId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'tokenAddress',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'price',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'buyer',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'bytes32',
				name: 'status',
				type: 'bytes32',
			},
		],
		name: 'TokenOfferUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'adr',
				type: 'address',
			},
		],
		name: 'Unauthorized',
		type: 'event',
	},
	{
		inputs: [],
		name: 'ACTIVE_STATUS',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'CANCELLED_STATUS',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'FINALIZED_STATUS',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'REJECTED_STATUS',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'REMOVED_STATUS',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: '_devWallet',
		outputs: [
			{ internalType: 'address payable', name: '', type: 'address' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
		],
		name: '_nftOffersByCollection',
		outputs: [
			{ internalType: 'uint256', name: 'nftOfferId', type: 'uint256' },
			{ internalType: 'address', name: 'buyer', type: 'address' },
			{
				internalType: 'address',
				name: 'soldNftAddress',
				type: 'address',
			},
			{
				internalType: 'address',
				name: 'wantedNftAddress',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'wantedNftId', type: 'uint256' },
			{ internalType: 'bytes32', name: 'status', type: 'bytes32' },
			{ internalType: 'uint256', name: 'index', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
		],
		name: '_tokenOffersByCollection',
		outputs: [
			{ internalType: 'uint256', name: 'tokenOfferId', type: 'uint256' },
			{ internalType: 'address', name: 'tokenAddress', type: 'address' },
			{ internalType: 'uint256', name: 'nftId', type: 'uint256' },
			{ internalType: 'address', name: 'nftAddress', type: 'address' },
			{ internalType: 'uint256', name: 'price', type: 'uint256' },
			{ internalType: 'address', name: 'buyer', type: 'address' },
			{ internalType: 'bytes32', name: 'status', type: 'bytes32' },
			{ internalType: 'uint256', name: 'index', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'acceptNFTOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'acceptTokenOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'addBNBToRewardContract',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'adminRemoveNFTOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'adminRemoveTokenOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_tokenAddress', type: 'address' },
			{ internalType: 'uint256', name: '_minimumValue', type: 'uint256' },
		],
		name: 'adminSetMinimumOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'adr', type: 'address' }],
		name: 'authorize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'blacklist',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'cancelNFTOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'cancelTokenOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'address', name: '_paymentNFT', type: 'address' },
			{
				internalType: 'uint256[]',
				name: '_offeredIds',
				type: 'uint256[]',
			},
		],
		name: 'createNFTOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'address', name: 'offeredToken', type: 'address' },
			{ internalType: 'uint256', name: 'offeredAmount', type: 'uint256' },
		],
		name: 'createTokenOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getAcceptableOfferedNFTs',
		outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getAcceptablePaymentNFTs',
		outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getAcceptablePaymentTokens',
		outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'globalMinimumOffers',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr_', type: 'address' }],
		name: 'isAcceptableOfferedNFT',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr_', type: 'address' }],
		name: 'isAcceptablePaymentNFT',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr_', type: 'address' }],
		name: 'isAcceptablePaymentToken',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'adr', type: 'address' }],
		name: 'isAuthorized',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
		name: 'isOwner',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'marketRewards',
		outputs: [
			{
				internalType: 'contract MarketRewards',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'address', name: '', type: 'address' },
		],
		name: 'minimumOffers',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'nftOfferId',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'nftOffers',
		outputs: [
			{ internalType: 'uint256', name: 'nftOfferId', type: 'uint256' },
			{ internalType: 'address', name: 'buyer', type: 'address' },
			{
				internalType: 'address',
				name: 'soldNftAddress',
				type: 'address',
			},
			{
				internalType: 'address',
				name: 'wantedNftAddress',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'wantedNftId', type: 'uint256' },
			{ internalType: 'bytes32', name: 'status', type: 'bytes32' },
			{ internalType: 'uint256', name: 'index', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'offerPaused',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'bytes', name: '', type: 'bytes' },
		],
		name: 'onERC721Received',
		outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'pendingRewards',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'rejectNFTOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_offerId', type: 'uint256' },
		],
		name: 'rejectTokenOffer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'router',
		outputs: [
			{ internalType: 'contract IDEXRouter', name: '', type: 'address' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'addr_', type: 'address' },
			{ internalType: 'bool', name: 'acceptable_', type: 'bool' },
		],
		name: 'setAcceptableOfferedNFT',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'addr_', type: 'address' },
			{ internalType: 'bool', name: 'acceptable_', type: 'bool' },
		],
		name: 'setAcceptablePaymentNFT',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'addr_', type: 'address' },
			{ internalType: 'bool', name: 'acceptable_', type: 'bool' },
		],
		name: 'setAcceptablePaymentToken',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr', type: 'address' }],
		name: 'setDevWallet',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bool', name: '_paused', type: 'bool' }],
		name: 'setIsOfferPaused',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr_', type: 'address' }],
		name: 'setMarketReward',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'address', name: '_tokenAddress', type: 'address' },
			{ internalType: 'uint256', name: '_minimumValue', type: 'uint256' },
		],
		name: 'setMinimumOfferByCollectionAndId',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'nftAddress_', type: 'address' },
			{ internalType: 'uint256[]', name: 'nftIds_', type: 'uint256[]' },
			{ internalType: 'address', name: 'tokenAddress_', type: 'address' },
			{ internalType: 'uint256', name: 'minimumValue_', type: 'uint256' },
		],
		name: 'setMinimumOffersByCollection',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr', type: 'address' }],
		name: 'setRouter',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'addr_', type: 'address' }],
		name: 'swapForRewards',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'swapForRewards',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'tokenOfferId',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'tokenOffers',
		outputs: [
			{ internalType: 'uint256', name: 'tokenOfferId', type: 'uint256' },
			{ internalType: 'address', name: 'tokenAddress', type: 'address' },
			{ internalType: 'uint256', name: 'nftId', type: 'uint256' },
			{ internalType: 'address', name: 'nftAddress', type: 'address' },
			{ internalType: 'uint256', name: 'price', type: 'uint256' },
			{ internalType: 'address', name: 'buyer', type: 'address' },
			{ internalType: 'bytes32', name: 'status', type: 'bytes32' },
			{ internalType: 'uint256', name: 'index', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address payable', name: 'adr', type: 'address' },
		],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'transferToDevWallet',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'adr', type: 'address' }],
		name: 'unauthorize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_index', type: 'uint256' }],
		name: 'viewNftOfferAt',
		outputs: [
			{
				components: [
					{
						internalType: 'uint256',
						name: 'nftOfferId',
						type: 'uint256',
					},
					{ internalType: 'address', name: 'buyer', type: 'address' },
					{
						internalType: 'address',
						name: 'soldNftAddress',
						type: 'address',
					},
					{
						internalType: 'uint256[]',
						name: 'soldNftIds',
						type: 'uint256[]',
					},
					{
						internalType: 'address',
						name: 'wantedNftAddress',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'wantedNftId',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'status',
						type: 'bytes32',
					},
					{ internalType: 'uint256', name: 'index', type: 'uint256' },
				],
				internalType: 'struct GhostOffers.NftOffer',
				name: '_nftOffer',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_cursor', type: 'uint256' },
			{ internalType: 'uint256', name: '_size', type: 'uint256' },
		],
		name: 'viewNftOffersByCollectionAndId',
		outputs: [
			{
				components: [
					{
						internalType: 'uint256',
						name: 'nftOfferId',
						type: 'uint256',
					},
					{ internalType: 'address', name: 'buyer', type: 'address' },
					{
						internalType: 'address',
						name: 'soldNftAddress',
						type: 'address',
					},
					{
						internalType: 'uint256[]',
						name: 'soldNftIds',
						type: 'uint256[]',
					},
					{
						internalType: 'address',
						name: 'wantedNftAddress',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'wantedNftId',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'status',
						type: 'bytes32',
					},
					{ internalType: 'uint256', name: 'index', type: 'uint256' },
				],
				internalType: 'struct GhostOffers.NftOffer[]',
				name: '_offers',
				type: 'tuple[]',
			},
			{ internalType: 'uint256', name: '', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'viewNftOffersLength',
		outputs: [{ internalType: 'uint256', name: 'size', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
		],
		name: 'viewNftOffersLengthByCollectionAndId',
		outputs: [{ internalType: 'uint256', name: 'size', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '_index', type: 'uint256' }],
		name: 'viewTokenOfferAt',
		outputs: [
			{
				components: [
					{
						internalType: 'uint256',
						name: 'tokenOfferId',
						type: 'uint256',
					},
					{
						internalType: 'address',
						name: 'tokenAddress',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'nftId', type: 'uint256' },
					{
						internalType: 'address',
						name: 'nftAddress',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'price', type: 'uint256' },
					{ internalType: 'address', name: 'buyer', type: 'address' },
					{
						internalType: 'bytes32',
						name: 'status',
						type: 'bytes32',
					},
					{ internalType: 'uint256', name: 'index', type: 'uint256' },
				],
				internalType: 'struct GhostOffers.TokenOffer',
				name: '_tokenOffer',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
			{ internalType: 'uint256', name: '_cursor', type: 'uint256' },
			{ internalType: 'uint256', name: '_size', type: 'uint256' },
		],
		name: 'viewTokenOffersByCollectionAndId',
		outputs: [
			{
				components: [
					{
						internalType: 'uint256',
						name: 'tokenOfferId',
						type: 'uint256',
					},
					{
						internalType: 'address',
						name: 'tokenAddress',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'nftId', type: 'uint256' },
					{
						internalType: 'address',
						name: 'nftAddress',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'price', type: 'uint256' },
					{ internalType: 'address', name: 'buyer', type: 'address' },
					{
						internalType: 'bytes32',
						name: 'status',
						type: 'bytes32',
					},
					{ internalType: 'uint256', name: 'index', type: 'uint256' },
				],
				internalType: 'struct GhostOffers.TokenOffer[]',
				name: '_offers',
				type: 'tuple[]',
			},
			{ internalType: 'uint256', name: '', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'viewTokenOffersLength',
		outputs: [{ internalType: 'uint256', name: 'size', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_nftAddress', type: 'address' },
			{ internalType: 'uint256', name: '_nftId', type: 'uint256' },
		],
		name: 'viewTokenOffersLengthByCollectionAndId',
		outputs: [{ internalType: 'uint256', name: 'size', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'wbnbAddress',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{ stateMutability: 'payable', type: 'receive' },
];
export default OfferABI;
