const ectoRewardDistributorAbi = [
	{
		inputs: [
			{ internalType: 'address', name: '_router', type: 'address' },
			{ internalType: 'address', name: '_rewardToken', type: 'address' },
		],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'rewardToken',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'totalDividends',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'dividendsPerShare',
				type: 'uint256',
			},
		],
		name: 'Deposited',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'uint256',
				name: 'newMinPeriod',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'newMinDistribution',
				type: 'uint256',
			},
		],
		name: 'DistributionCriteriaChanged',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'shareholder',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'totalExcluded',
				type: 'uint256',
			},
		],
		name: 'HolderShareChanged',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'uint256',
				name: 'gasUsed',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'gasLeft',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'currentIndex',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'iterations',
				type: 'uint256',
			},
		],
		name: 'Processed',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'token',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'bool',
				name: 'chargeTxFee',
				type: 'bool',
			},
		],
		name: 'RewardTokenChanged',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: '_router',
				type: 'address',
			},
		],
		name: 'RouterChanged',
		type: 'event',
	},
	{
		inputs: [],
		name: 'claimDividend',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'currentIndex',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'deposit',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'dividendsPerShare',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'dividendsPerShareAccuracyFactor',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getDistributorState',
		outputs: [
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getShareHolders',
		outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getTokenGuard',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'shareholder', type: 'address' },
		],
		name: 'getUnpaidEarnings',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address[]',
				name: '_shareHolders',
				type: 'address[]',
			},
			{
				internalType: 'uint256[]',
				name: '_shareholderIndexes',
				type: 'uint256[]',
			},
			{
				internalType: 'uint256[]',
				name: '_shareholderClaims',
				type: 'uint256[]',
			},
			{ internalType: 'uint256[]', name: '_amounts', type: 'uint256[]' },
			{
				internalType: 'uint256[]',
				name: '_totalExcludes',
				type: 'uint256[]',
			},
			{
				internalType: 'uint256[]',
				name: '_totalRealises',
				type: 'uint256[]',
			},
			{ internalType: 'uint256', name: '_currentIndex', type: 'uint256' },
			{ internalType: 'uint256', name: '_totalShares', type: 'uint256' },
			{
				internalType: 'uint256',
				name: '_totalDividends',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: '_totalDistributed',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: '_dividendsPerShare',
				type: 'uint256',
			},
		],
		name: 'migrateDistributorStates',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'minDistribution',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'minPeriod',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'gas', type: 'uint256' }],
		name: 'process',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'newMinPeriod', type: 'uint256' },
			{
				internalType: 'uint256',
				name: 'newMinDistribution',
				type: 'uint256',
			},
		],
		name: 'setDistributionCriteria',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'token', type: 'address' },
			{ internalType: 'bool', name: 'chargeTxFee', type: 'bool' },
		],
		name: 'setRewardToken',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '_router', type: 'address' }],
		name: 'setRouter',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'shareholder', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'setShare',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'shareholderClaims',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'shareholderIndexes',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'shares',
		outputs: [
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			{ internalType: 'uint256', name: 'totalExcluded', type: 'uint256' },
			{ internalType: 'uint256', name: 'totalRealised', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalDistributed',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalDividends',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalShares',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
];

export default ectoRewardDistributorAbi;
