const ectoSkeletonsFilters = {
	Background: [
		'Broomstick Brown',
		'Bunny Cloud',
		'Cold Ice',
		'Cotton Candy',
		'Ghastly Grey',
		'Ghost Blue',
		'Gravestone Grey',
		'Grim Grey',
		'Halloween punch',
		'Hydra gray',
		'Jade',
		'Lagoon',
		'Luxor gold',
		'Midnight Magic',
		'Moonscape',
		'Muted green',
		'Nautical',
		'Nebulous',
		'Neon blue',
		'Pastel red',
		'Peach fury',
		'Phantom ship',
		'Pink floyd',
		'Pisco sour',
		'Purple Potion',
		'Vanilla',
		'Vineyard',
		'Whales tale',
		'Wicked green',
	],
	Body: [
		'Green Skeleton',
		'Ice King Skeleton',
		'Purple Skeleton',
		'Red Skeleton',
		'Tan Skeleton',
		'White Skeleton',
	],
	Buffs: [
		'Archery Attack % (Tier I)',
		'Archery Attack % (Tier II)',
		'Archery Attack % (Tier III)',
		'Archery Defense % (Tier I)',
		'Archery Defense % (Tier II)',
		'Archery Defense % (Tier III)',
		'Backpack Slot (Tier I)',
		'Backpack Slot (Tier II)',
		'Backpack Slot (Tier III)',
		'Energy % (Tier I)',
		'Energy % (Tier II)',
		'Energy % (Tier III)',
		'Healing % (Tier I)',
		'Healing % (Tier II)',
		'Healing % (Tier III)',
		'Healing Regeneration (Tier I)',
		'Healing Regeneration (Tier II)',
		'Healing Regeneration (Tier III)',
		'HP % (Tier I)',
		'HP % (Tier II)',
		'HP % (Tier III)',
		'Magic Attack % (Tier I)',
		'Magic Attack % (Tier II)',
		'Magic Attack % (Tier III)',
		'Magic Defense % (Tier I)',
		'Magic Defense % (Tier II)',
		'Magic Defense % (Tier III)',
		'Melee Attack % (Tier I)',
		'Melee Attack % (Tier II)',
		'Melee Attack % (Tier III)',
		'Melee Defense % (Tier I)',
		'Melee Defense % (Tier II)',
		'Melee Defense % (Tier III)',
		'Special Regeneration (Tier I)',
		'Special Regeneration (Tier II)',
		'Special Regeneration (Tier III)',
	],
	Eyes: [
		'Angry Blue Jewel Eyes',
		'Angry Blue Retro Sunglasses',
		'Angry Eyes',
		'Angry Gold Jewel Eyes',
		'Angry Green Jewel Eyes',
		'Angry Hallow Eyes',
		'Angry Ice Jewel Eyes',
		'Angry Pink Retro Sunglasses',
		'Angry Purple Jewel Eyes',
		'Angry Purple Jewel Mascara Eyes',
		'Angry Red Jewel Eyes',
		'None',
		'Normal Blue Jewel Eyes',
		'Normal Eyes',
		'Normal Gold Jewel Eyes',
		'Normal Green Jewel Eyes',
		'Normal Purple Jewel Eyes',
		'Normal Red Jewel Eyes',
		'Regular Hallow Eyes',
		'Sad Eyes',
		'Sad Hallow Eyes',
	],
	Hat: [
		'Beanie',
		'Black Cap',
		'Blue Flaming Head',
		'Bucket Hat Black',
		'Bucket Hat Grey',
		'Bunny Ears',
		'Clown',
		'Cowboy Hat',
		'Diamond Mask',
		'Evil Beetle Wig',
		'Evil Horns',
		'Fish Bowel',
		'Flaming Head',
		'Gold Crown',
		'Green Cap',
		'Green Flaming Head',
		'Grey Cap',
		'Halo',
		'Jewel Crown',
		'None',
		'Red Cap',
		'Santa Hat',
		'Silver Crown',
		'Skii Mask',
	],
	Item: [
		'Blue Balloon',
		'Blunt',
		'Bubble Stick',
		'Cigarette',
		'Glock',
		'Green Balloon',
		'Knife',
		'None',
		'Pink Balloon',
		'Purple Balloon',
		'Red Balloon',
		'Rose',
		'Scythe',
		'Slendy Tentacles',
		'Ye Mic',
		'Yellow Balloon',
	],
	Mouth: [
		'Laughing Gold Grill Mouth',
		'Laughing Green Grill Mouth',
		'Laughing Mouth',
		'Laughing Rainbow Grill Mouth',
		'None',
		'Normal Mouth',
		'Sad Mouth',
		'Shocked Mouth',
		'Shocked Mouth Tongue',
		'Slightly Open Mouth',
	],
	Top: [
		'Black Hoodie Down',
		'Black Hoodie Up',
		'Black Hoodie Up Red Tie',
		'Black T-shirt',
		'Evil Beetle Suit',
		'Gold Chain',
		'Gold Chain on Pink Hoodie',
		'Grey Hoodie Down',
		'Grey Hoodie Up',
		'Grey T-shirt',
		'Jack Suit',
		'None',
		'Pink Hoodie',
		'Reaper Black Hoodie Up',
		'White Shirt',
	],
};

export default ectoSkeletonsFilters;
