const littleGhostsFilters = {
	Background: [
		'Asagi',
		'Cool Magenta',
		'Cyan',
		'Dark Mustard',
		'Emperor',
		'Epic Blue',
		'Foggy Grey',
		'Ghost Green',
		'Gravel Grey',
		'Haunted Plum',
		'Lava Red',
		'Maximum Yellow',
		'Midnight Blue',
		'Midnight Green',
		'Moss Green',
		'Pale Berry',
		'Pale Orange',
		'Pumpkin Orange',
		'Punk Blue',
		'Razzmic Berry',
		'Silk Blue',
		'Silk Bulk',
		'Slate Blue',
		'Wageningen Green',
	],
	Body: [
		'Alien Ghost',
		'Baby Ghost Alien',
		'Beetle Ghost',
		'Black Ghost',
		'Blue Alien Ghost',
		'Blue Ghost',
		'Dark Purple Ghost',
		'Doge Ghost',
		'Friendly Ghost',
		'Ghost Rick',
		'Ghostdu',
		'Ghostface Ghost',
		'Ghostie Wan',
		'Green Glowing Ghost',
		'Grey Ghost',
		'Hades',
		'Lime Green Ghost',
		'Pancake Ghost',
		'Purple Ghost',
		'Red Ghost',
		'Scary Ghost',
		'Shiba Ghost',
		'Super Shy Ghost',
		'Transparent Ghost',
		'White Ghost',
	],
	Buffs: [
		'+4 Every Bonus',
		'+5 Every Bonus',
		'+6 Every Bonus',
		'+8 Every Bonus',
	],
	Eyes: [
		'Alien Eyes',
		'Anime Black Eyes',
		'Anime Red Eyes',
		'Baby Ghost Alien Eyes',
		'Beetle Eyes',
		'Bubble Eyes',
		'Cross Eyes',
		'Evil Eyes',
		'Friendly Eyes',
		'Ghost Sith Eyes',
		'Ghostdu Eyes',
		'Ghostface Eyes',
		'Ghostie Wan Eyes',
		'Girly Eyes',
		'Green Ghost Eyes',
		'Hades',
		'Happy Eyes',
		'Heart Eyes',
		'Jawa Eyes',
		'Money Sign Eyes',
		'Pancake Eyes',
		'Rick Eyes',
		'Right Look',
		'Scary Eyes',
		'Squint Eyes',
		'Stare Eyes',
		'Stoned Eyes',
		'Super Shy Eyes',
		'Uninterested Look',
		'Vampire Eyes',
	],
	Hat: [
		'Baby Ghost Alien Hoodie',
		'Backwards Red Hat',
		'Beetle Hair',
		'Black Backwards ERTH Cap',
		'Black Backwards ERTH Hat',
		'Black Backwards Hat',
		'Black Baseball Cap',
		'Black Beanie',
		'Black ERTH Baseball Cap',
		'Black Hoodie',
		'Blue Flames',
		'Blue Wizard Hat',
		'Construction Hat',
		'Ghost Sith Hoodie',
		'Ghostdu Hoodie',
		'Ghostface Hoodie',
		'Ghostie Wan Hoodie',
		'Green Backwards Hat',
		'Green Baseball Cap',
		'Green Beanie',
		'Hoodie',
		'Jawa Hoodie',
		'None',
		'Orange Beanie',
		'Pancake Ears',
		'Purple Backwards Hat',
		'Purple Baseball Cap',
		'Purple Beanie',
		'Purple Wizard Hat',
		'Red Backwards Hat',
		'Red Baseball Cap',
		'Rick Hair',
		'Santa Hat',
		'Super Shy Hoodie',
		'Teal Beanie',
		'Top Hat',
	],
	Item: [
		'Bloody Knife',
		'Blue Lightsaber',
		'Bnb Coin',
		'Dripping Soul Knife',
		'ERTH',
		'Green Lightsaber',
		'Hanging Chain',
		'Jawa Gun',
		'Knife',
		'Money',
		'None',
		'Purple Lightsaber',
		'Red Lightsaber',
		'Ricks Laser Gun',
		'Trick Or Treat Bag',
	],
	Mouth: [
		'Alien Mouth',
		'Baby Ghost Alien Mouth',
		'Beetle Mouth',
		'Big Smile',
		'Cigarette',
		'Cigarette Smoke',
		'Face Mask',
		'Friendly Mouth',
		'Frown',
		'Ghost Sith Smile',
		'Ghostdu Mouth',
		'Ghostface Mouth',
		'Ghostie Wan Mouth',
		'Green Ghost Mouth',
		'Grill',
		'Hades',
		'None',
		'Rick Mouth',
		'Scary Mouth',
		'Scary Tounge Flick',
		'Smirk',
		'Stiches',
		'Straight',
		'Super Shy Mouth',
		'Vampire Teeth',
		'Wiggle Mouth',
	],
	Prop: [
		'3D Glasses',
		'Blue Lasers',
		'Cigarette',
		'Earrings',
		'Eye Patch',
		'Gold Chain',
		'Green Lasers',
		'Halo',
		'Heart Bubble',
		'Horns',
		'None',
		'Red Lasers',
		'Silver Chain',
		'Sunglasses',
		'Underworld Robe',
	],
};
export default littleGhostsFilters;
